* CRUX
** How does the OS manage the persistent storage ?
** What API is provided to the user ?
** What is important when implement this API ?

* File System just give two blobs: file and directory

* Open file System
** Each proc (struct proc) have a file struct array files[OFILE]. In file struct OS will maintain the offset, permissions, ref, ... If one file was opened twice, it will be allocated two different file struct.
** In the system there is a ftable will represent all of the opened files in the system. If one file was opened twice, it will also have two entries in OFT. You can break this by the fork() and dup*() syscall.
** Because of the performance thinking, system may buffer the changes of the underlying disks, use fsync() to enforce the write-back, **IMPORTANT**, not only fsync the file, but also the parent directory.

* COMMENT mmap syscall
** you can use mmap to map a disk part into memory so that you can use memory operation instructions to handle disk content. The corresponding chapter give a example to implement a persistent memory based stack data structure.

* Summary
** For a summary of terms in file system, lookaside the corresponding chapter's last Aside(Files and Directories). 

* CRUX
** How to build a filesystem than support the last chapter talked files and directories ... operations

* Two important questions
** fs use what data structures to store the file's content ?
** How does the fs mapping the syscall to the corresponding disk operations ?

* Inode -> Indexed node
** inode is just a data structure used to store metadata, so you can use your way to do this, no essential *inode*. 
** In inode, for locate the data block, you can choose to store the pointer of the data block, this is not convenient for large files, in this case, you may need to use multi-level indexing. Another way is use extent, something like segment in VM.

* Directory management
** Directory's inode is just like regular files', but the filetype will told you it is indeed a directory instead of a regular file. The data block store the tuple of user-friendly name and inumber, also a little extra information.

* Performance
** We have the ways to implement the support for file and directory, but this need extremely high I/O cost. Batch, scheduling, delaying are common ways to improve. For some applications, they may choose to skip the OS to directly commuciate with the disk.
