#+AUTHOR: doodo
#+EMAIL: 2901652008@qq.com
#+DESCRIPTION: Record the **shit** from everywhere

* Real shit will be smelled anywhere
- Can I write a text program which is also the binary executable ? <2026-06-15 Mon 10:11>
- How about use QEMU to boot a physical disk instead of a virtual one ? Such as in my SSD, there are Linux and Windows, can I boot linux, then use QEMU to boot the Windows partition ? I have search some posts, but failed, maybe at some leisure time this is a is a good play :) <2026-07-17 Fri 20:51>
- As I known, the original computer program is hardcoded circuit, so every you need to test your program, you need to rearrange the circuit. Before this is obselete, but nowadays I feel the development of general AI is slow, why we just hardcoded all the AI logic in a circuit ? Because the respone speed is also important when using it. After some search, I found already have somebody done this, and share this like a website. That's a good direction in the furture. <2026-07-17 Fri 20:54>
- Noone can stop the scale law of AI. I am thinking what the future of Math will be. Basically we're trying to find a **new** way to explain the world generally. AI currently don't have this competence. So I think our human beings can continuely think about a better, a general way to explain the nature, then use AI to verify which road is correct just by using new theory to prove exist theorems. AI just follow your logic to do all the inference. Then if there are limitless tokens, **everyone can use his own way to explain the world, only need to guarantee that his thoery can explain various phenomena**. The exist theory architecture is just a /standard/ or sometimes a /prompt/ for us to shape our theory better. <2026-09-05 Sat 10:19>
